### ISSUE TITLE
Update Contact us Section

### ISSUE THREAD

**Issue by menikhilpandey** [SD-DTU/sd-dtu.github.io#12]
Update Title of this section to Work with us. 
The form for same must include:
Name, Contact Phone, Email Address, 
What kind of work you're interested to do with us? (Look for better phrase for this)
Further Description
How you got to know about us?
Form must be sent to our email, sddtu@protonmail.com along with a thanks page modal to be implemented.

**Comment by dhruvramdev** [comment]
Check Pull Request Regarding This
